CREATE TABLE IF NOT EXISTS accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE,
  password BLOB NOT NULL,
  form_data BLOB
);

CREATE INDEX IF NOT EXISTS email_idx ON accounts (email);

CREATE TABLE IF NOT EXISTS keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key BLOB NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

