name: server-build

on:
  push:
    branches: master

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    environment: server-build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/btburke/vatinator/server:latest
            ghcr.io/btburke/vatinator/server:${{github.run_number}}
          build-args: |
            GITHUB_SHA
            GITHUB_RUN_NUMBER
